import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'
import React from 'react'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import Navbar from '@/app/_components/navbar'
import '../globals.css'

export const mulish = Mulish({
    subsets: ['latin-ext'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function PrivateLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider appearance={{ baseTheme: dark }}>
            <html lang="pt-BR">
                <body className={`${mulish.className} antialiased dark`}>
                    <Navbar />
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}
